.TH "autosd" 1 "2016-02-07" "Linux User's Manual"


.SH NAME

.P
\fBautosd\fR checks for the presence of mains power, if absent and battery
falls below a user specified level it monitors the situation more
closely until the battery falls to another lower level and then shuts
the system down. Any time before that event, restored power causes the
program to quit.

.SH SYNOPSIS

.P
\fBautosd\fR [option]

.SH DESCRIPTION

.P
\fBautosd\fR is intended to be used as a cron job to check the power
status of a laptop. When mains power is off the program takes no action
until the battery charge level falls below a point called the
\fImonitor_level\fR. At this point the program continually checks the
battery status every \fIcheck_interval\fR minutes and if the battery falls
to \fIquit_level\fR it will shut the system down. If at any check the
mains power has been restored the program simply quits.

.P
These parameters \fImonitor_level\fR, \fIcheck_interval\fR and
\fIquit_level\fR are read from a configuration file located at
\fI$HOME/.config/autosd/autosd.cfg\fR. The user should set these
parameters to suit his machine and the unattended processing load it
performs.

.SH OPTIONS

.TP
 \fB\-h\fR, \fB\-\-help\fR
prints help information and exits.

.TP
 \fB\-m\fR, \fB\-\-monitor\fR
run from a console using this option with the mains power turned off.
From the knowledge gained set the parameters in the config file to suit
your machine and it's use.

.SH AUTHOR

.P
Robert L Parker rlp1938@gmail.com

.\" man code generated by txt2tags 2.6 (http://txt2tags.org)
.\" cmdline: txt2tags -t man autosd.t2t
